<a href="https://colab.research.google.com/github/s-rafia/Samsung-Innovation-Campus-AI-Training/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Install Pandas**

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

# **Series**

In [ ]:
data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

**Series with custom index**

In [ ]:
s = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
print(s)

a    100
b    200
c    300
dtype: int64

**Access Series Data**

In [ ]:
print(s['a'])
print(s[0])

100
100

/tmp/ipython-input-441/1148839198.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

# **Practice 1:**
- Create a Series of 5 student marks
- Assign subject names as index
- Print one value using index name

In [ ]:
stu = pd.Series([85, 78, 92, 74, 88], index=["Math", "Science", "English", "History", "Art"])
print(stu["Art"])

88

**Series From Dictionary**

In [ ]:
data = {"Math": 85, "English": 90, "Science": 88}
s = pd.Series(data)
print(s)

Math       85
English    90
Science    88
dtype: int64

Accessing Values - Series Dictioneries

In [ ]:
s["Math"]

np.int64(85)

In [ ]:
s[0]

/tmp/ipython-input-441/243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]

np.int64(85)

**Arithmetic Operations**

In [ ]:
s + 5

Math       90
English    95
Science    93
dtype: int64

In [ ]:
s * 2

Math       170
English    180
Science    176
dtype: int64

In [ ]:
s % 3

Math       1
English    0
Science    1
dtype: int64

**Comparison Operations**

In [ ]:
s > 85

Math       False
English     True
Science     True
dtype: bool

In [ ]:
s < 90

Math        True
English    False
Science     True
dtype: bool

In [ ]:
s == 90

Math       False
English     True
Science    False
dtype: bool

In [ ]:
s != 88

Math        True
English     True
Science    False
dtype: bool

**Filtering Using Conditions**

In [ ]:
s[s > 85]

English    90
Science    88
dtype: int64

In [ ]:
s[s < 90]

Math       85
Science    88
dtype: int64

In [ ]:
s[s % 2 == 0]

English    90
Science    88
dtype: int64

**Series vs Series (Index Alignment Concept)**

In [ ]:
s1 = pd.Series([10, 20, 30], index = ["A", "B", "C"])
s2 = pd.Series([1, 2, 3], index = ["A", "B", "C"])
s1 + s2

A    11
B    22
C    33
dtype: int64

In [ ]:
s1 - s2

A     9
B    18
C    27
dtype: int64

In [ ]:
s1 * s2

A    10
B    40
C    90
dtype: int64

**Built-in Mathematical Functions**

In [ ]:
s.sum()

np.int64(263)

In [ ]:
s.mean()

np.float64(87.66666666666667)

In [ ]:
s.max()

90

In [ ]:
s.min()

85

In [ ]:
s.count()

np.int64(3)

In [ ]:
s.std()

2.516611478423583

**Utility Functions**

In [ ]:
s.isnull()

Math       False
English    False
Science    False
dtype: bool

In [ ]:
s.replace(90, 100)

Math        85
English    100
Science     88
dtype: int64

In [ ]:
s.sort_values()

Math       85
Science    88
English    90
dtype: int64

In [ ]:
s.sort_values(ascending= False)

English    90
Science    88
Math       85
dtype: int64

In [ ]:
s.unique()

array([85, 90, 88])

# **DataFrame**

**Creating DataFrames - Dictioneries**

In [ ]:
data = {
    'Name': ['Ali', 'Sara', 'Ahmed'],
    'Age': [20, 22, 21],
    'Marks': [85, 90, 88]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0    Ali   20     85
1   Sara   22     90
2  Ahmed   21     88

**From List of Lists**

In [ ]:
data = [
    ['Ali', 20, 85],
    ['Sara', 22, 90],
    ['Ahmed', 21, 88]
]

df = pd.DataFrame(data, columns = ['Name', 'Age', 'Marks'])
print(df)

    Name  Age  Marks
0    Ali   20     85
1   Sara   22     90
2  Ahmed   21     88

# **Practice 2**
Create a DataFrame with:
- Student Name
- Subject
- Marks
- (Add at least 4 students)

**From Dictionries**

In [ ]:
std = {
    'Name': ['Ali', 'Saad', 'Ahmed', 'Sara'],
    'Subject': ['Math', 'Science', 'English', 'Arts'],
    'Marks': [85, 45, 77, 90]
}

df = pd.DataFrame(std)
print(df)

    Name  Subject  Marks
0    Ali     Math     85
1   Saad  Science     45
2  Ahmed  English     77
3   Sara     Arts     90

**From Lists**

In [ ]:
std = [
    ['Ali', 'Math', 85],
    ['Saad', 'Science', 45],
    ['Ahmed', 'English', 77],
    ['Sara', 'Arts', 90]
]

df= pd.DataFrame(std, columns = ['Name', 'Subject', 'Marks'])
print(df)

    Name  Subject  Marks
0    Ali     Math     85
1   Saad  Science     45
2  Ahmed  English     77
3   Sara     Arts     90

# **Viewing Data**

**1. df.head()**

In [ ]:
df.head()

    Name  Subject  Marks
0    Ali     Math     85
1   Saad  Science     45
2  Ahmed  English     77
3   Sara     Arts     90

In [ ]:
df.head(2)

   Name  Subject  Marks
0   Ali     Math     85
1  Saad  Science     45

**2. df.tail()**

In [ ]:
df.tail()

    Name  Subject  Marks
0    Ali     Math     85
1   Saad  Science     45
2  Ahmed  English     77
3   Sara     Arts     90

In [ ]:
df.tail(1)

   Name Subject  Marks
3  Sara    Arts     90

**3. df.info()**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     4 non-null      object
 1   Subject  4 non-null      object
 2   Marks    4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

**4. df.shape**

In [ ]:
df.shape

(4, 3)

In [ ]:
df.shape[0]

4

In [ ]:
df.shape[1]

3

**5. df.columns()**

In [ ]:
df.columns

Index(['Name', 'Subject', 'Marks'], dtype='object')

# **Data Selection & Indexing**

**1. Select Column**

In [ ]:
df['Name']

0      Ali
1     Saad
2    Ahmed
3     Sara
Name: Name, dtype: object

**2. Select Multiple Columns**

In [ ]:
df[['Name', 'Marks']]

    Name  Marks
0    Ali     85
1   Saad     45
2  Ahmed     77
3   Sara     90

**3. Select Rows by Index**

In [ ]:
df.loc[0]

Name        Ali
Subject    Math
Marks        85
Name: 0, dtype: object

In [ ]:
df.iloc[1]

Name          Saad
Subject    Science
Marks           45
Name: 1, dtype: object

# **Practice 3**
1. Print only Marks column
2. Print first row
3. Print marks of first student

In [ ]:
df['Marks']

0    85
1    45
2    77
3    90
Name: Marks, dtype: int64

In [ ]:
df.loc[0]

Name        Ali
Subject    Math
Marks        85
Name: 0, dtype: object

In [ ]:
df['Marks'].loc[0]

np.int64(85)

# **Adding & Removing Columns**

**1. Add Column**

In [ ]:
df['Grade'] = ['A', 'C', 'B', 'A+']
df

    Name  Subject  Marks Grade
0    Ali     Math     85     A
1   Saad  Science     45     C
2  Ahmed  English     77     B
3   Sara     Arts     90    A+

**2. Remove Column**

In [ ]:
df.drop('Grade', axis=1, inplace=True, errors='ignore')
df

    Name  Subject  Marks
0    Ali     Math     85
1   Saad  Science     45
2  Ahmed  English     77
3   Sara     Arts     90

# **Handling Missing Data**

**Create Missing Data**

In [ ]:
import numpy as np

data = {
    'Name': ['Ali', 'Sara', 'Ahmed'],
    'Marks': [85, np.nan, 90]
}

df = pd.DataFrame(data)
df

    Name  Marks
0    Ali   85.0
1   Sara    NaN
2  Ahmed   90.0

**Detect Missing Values**

In [ ]:
df.isnull()

    Name  Marks
0  False  False
1  False   True
2  False  False

In [ ]:
df.isnull().sum()

Name     0
Marks    1
dtype: int64

**Remove Missing Data**

In [ ]:
df.dropna()

    Name  Marks
0    Ali   85.0
2  Ahmed   90.0

Fill Missing Data

In [ ]:
df.fillna(0)

    Name  Marks
0    Ali   85.0
1   Sara    0.0
2  Ahmed   90.0

In [ ]:
df['Marks'].fillna(df['Marks'].mean())

0    85.0
1    87.5
2    90.0
Name: Marks, dtype: float64

# **Practice 4**
- Create a DataFrame with one missing value
- Replace missing value with average

In [ ]:
data = [
    ['Ali', 85],
    ['Sara', np.nan],
    ['Ahmed', 90]
]

df = pd.DataFrame(data, columns= ['Name', 'Marks'])
df

    Name  Marks
0    Ali   85.0
1   Sara    NaN
2  Ahmed   90.0

In [ ]:
df['Marks'].fillna(df['Marks'].mean())

0    85.0
1    87.5
2    90.0
Name: Marks, dtype: float64

# **CVS Files**

**Loading CVS File**

In [ ]:
from google.colab import files
upload = files.upload()

Saving data_Iris.csv to data_Iris.csv

In [ ]:
import pandas as pd
df = pd.read_csv('data_Iris.csv')

df.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# **Practice 5:**
Inspecting Data
1. df.head()
2. df.tail()
3. df.shape() *Returns (rows, columns)*
4. df.columns()
5. df.info() *Data types-Missing values-No. of rows*
6. df.describe() *Only numerical columns-mean, std, min, max*

In [ ]:
df.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.tail()

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
df.shape

(150, 5)

In [ ]:
df.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df.describe()

       Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

**Selecting Data**

In [ ]:
df['Sepal.Length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal.Length, Length: 150, dtype: float64

In [ ]:
df[['Sepal.Length', 'Petal.Length']]

     Sepal.Length  Petal.Length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

**Selecting Rows Using iloc (Position Based)**

In [ ]:
df.iloc[0]

Sepal.Length       5.1
Sepal.Width        3.5
Petal.Length       1.4
Petal.Width        0.2
Species         setosa
Name: 0, dtype: object

In [ ]:
df.iloc[0:5]

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

**Conditional Filtering**

In [ ]:
df[df['Species'] == 'setosa']

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.1           1.5          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [ ]:
df[df['Sepal.Length'] > 5]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[118 rows x 5 columns]