<a href="https://colab.research.google.com/github/s-rafia/Samsung-Innovation-Campus-AI-Training/blob/main/Pandas-working-with-excel-file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

This way the imported file is on cloud not on local server

In [ ]:
from google.colab import files
upload = files.upload()

Saving std-data.xlsx to std-data (1).xlsx

This way the imported file is on local server

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/std-data.xlsx")

In [ ]:
df.info(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   S. No   5 non-null      int64
 1   Name    5 non-null      object
 2   Age     5 non-null      int64
 3   Marks   5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

In [ ]:
df.describe()

          S. No       Age      Marks
count  5.000000   5.00000   5.000000
mean   3.000000  21.80000  71.600000
std    1.581139   1.48324  14.536162
min    1.000000  20.00000  55.000000
25%    2.000000  21.00000  58.000000
50%    3.000000  22.00000  78.000000
75%    4.000000  22.00000  78.000000
max    5.000000  24.00000  89.000000

In [ ]:
df.shape

(5, 4)

In [ ]:
df = pd.read_excel("/content/std-data.xlsx")

In [ ]:
print(df)

   S. No   Name  Age  Marks
0      1    Ali   20     78
1      2  Ahmed   21     58
2      3   Atif   22     89
3      4  Ammar   24     78
4      5  Wasay   22     55

In [ ]:
df.head()

   S. No   Name  Age  Marks
0      1    Ali   20     78
1      2  Ahmed   21     58
2      3   Atif   22     89
3      4  Ammar   24     78
4      5  Wasay   22     55

In [ ]:
sd = pd.read_excel("/Book2.xlsx")

In [ ]:
print(sd.head(3))

   S.No. Students  Age  Marks
0      1       S1   25     85
1      2       S2   22     45
2      3       S3   24     76

In [ ]:
sd.columns

Index(['S.No.', 'Students', 'Age', 'Marks'], dtype='object')

In [ ]:
sd.info

<bound method DataFrame.info of    S.No. Students  Age  Marks
0      1       S1   25     85
1      2       S2   22     45
2      3       S3   24     76
3      4       S4   23     92>

In [ ]:
sd.describe()

          S.No.        Age      Marks
count  4.000000   4.000000   4.000000
mean   2.500000  23.500000  74.500000
std    1.290994   1.290994  20.728402
min    1.000000  22.000000  45.000000
25%    1.750000  22.750000  68.250000
50%    2.500000  23.500000  80.500000
75%    3.250000  24.250000  86.750000
max    4.000000  25.000000  92.000000

In [ ]:
sd.shape

(4, 4)

In [ ]:
sd.tail()

   S.No. Students  Age  Marks
0      1       S1   25     85
1      2       S2   22     45
2      3       S3   24     76
3      4       S4   23     92

In [ ]:
sd.head()

   S.No. Students  Age  Marks
0      1       S1   25     85
1      2       S2   22     45
2      3       S3   24     76
3      4       S4   23     92

In [ ]:
sd['Marks'] > 80

0     True
1    False
2    False
3     True
Name: Marks, dtype: bool

In [ ]:
sd = pd.read_excel("/Book2.xlsx")

In [ ]:
sd.isnull()

   S.No.  Students    Age  Marks
0  False     False  False  False
1  False     False  False  False
2  False     False  False  False
3  False     False  False  False
4  False     False  False  False
5  False     False   True  False
6  False     False  False  False

In [ ]:
data = {
    "Product": ["Pen", "Book", "Bag", "Shoes"],
    "Price": [10, 50, 500, 2000],
    "Stock": [100, 40, 20, 10]
}

df = pd.DataFrame(data)
print(df)

  Product  Price  Stock
0     Pen     10    100
1    Book     50     40
2     Bag    500     20
3   Shoes   2000     10

Products with price greater than 100

In [ ]:
price_gt_100 = df[df["Price"] > 100]
print("Products with price > 100: ")
print(price_gt_100)

Products with price > 100:
  Product  Price  Stock
2     Bag    500     20
3   Shoes   2000     10

Sort by stock

In [ ]:
sort_by_stock = df.sort_values(by="Stock")
print("\nSorted bt Stock:")
print(sort_by_stock)

Sorted bt Stock:
  Product  Price  Stock
3   Shoes   2000     10
2     Bag    500     20
1    Book     50     40
0     Pen     10    100

sort by product

In [ ]:
sort_by_product = df.sort_values(by="Product")
print("\nSorted bt Product:")
print(sort_by_product)

Sorted bt Product:
  Product  Price  Stock
2     Bag    500     20
1    Book     50     40
0     Pen     10    100
3   Shoes   2000     10

Adding a new column

In [ ]:
df["TotalValue"] = df["Price"] * df["Stock"]
print("\nDataFrame with TotalValue Column:")
print(df)

DataFrame with TotalValue Column:
  Product  Price  Stock  TotalValue
0     Pen     10    100        1000
1    Book     50     40        2000
2     Bag    500     20       10000
3   Shoes   2000     10       20000

Stock less than 30

In [ ]:
stock_lt_30 = df[df["Stock"] < 30]
print("\nProducts with Stock < 30")
print(stock_lt_30)

Products with Stock < 30
  Product  Price  Stock  TotalValue
2     Bag    500     20       10000
3   Shoes   2000     10       20000

In [ ]:
from google.colab import files
upload = files.upload()

Saving electronics_inventory.csv to electronics_inventory.csv

In [ ]:
ei = pd.read_csv("electronics_inventory.csv")

In [ ]:
print(ei)

     Products   Categories  Price  Stock
0      Laptop  Electronics    800     15
1  Headphones  Accessories    150     50
2       Mouse  Accessories     25    200
3  Smartphone  Electronics   1200      8
4    Keyboard  Accessories     75     60
5     Monitor  Electronics    300     25
6      Tablet  Electronics    600     12

Show products with price greater than 100

In [ ]:
price_gt_100 = ei[ei["Price"] > 100]
print("\nProducts with price greater than 100")
print(price_gt_100)

Products with price greater than 100
     Products   Categories  Price  Stock
0      Laptop  Electronics    800     15
1  Headphones  Accessories    150     50
3  Smartphone  Electronics   1200      8
5     Monitor  Electronics    300     25
6      Tablet  Electronics    600     12