<a href="https://colab.research.google.com/github/s-rafia/Samsung-Innovation-Campus-AI-Training/blob/main/Pandas-Series_DataFrames_Handling_Missing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Series (1D-Index)

In [ ]:
import pandas as pd

data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

Series with custom index

In [ ]:
s = pd.Series([100, 200, 300], index = ['a', 'b', 'c'])
print(s)

a    100
b    200
c    300
dtype: int64

Access Series Data

In [ ]:
print(s['a'])
print(s[0])

100
100

/tmp/ipython-input-1148839198.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

Practice 1

In [ ]:
m = pd.Series([85, 45, 77, 85, 90], index = ['Math', 'Science', 'English', 'History', 'Art'])
print(m['Art'])

90

Series from dictioneries


*   Key become index
*   Values become values

In [ ]:
data = {"Math": 85, "English": 90, "Science": 88}
s = pd.Series(data)
print(s)

Math       85
English    90
Science    88
dtype: int64

Access values - Series Dict

In [ ]:
s["Math"]

np.int64(85)

In [ ]:
s[0]

/tmp/ipython-input-243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]

np.int64(85)

Series Operations

In [ ]:
s + 5

Math       90
English    95
Science    93
dtype: int64

In [ ]:
s * 2

Math       170
English    180
Science    176
dtype: int64

In [ ]:
s ** 2

Math       7225
English    8100
Science    7744
dtype: int64

Comparission operarion

In [ ]:
s > 88

Math       False
English     True
Science    False
dtype: bool

In [ ]:
s != 90

Math        True
English    False
Science     True
dtype: bool

Filtering using conditions - These return boolean series

In [ ]:
s[s > 85]

English    90
Science    88
dtype: int64

In [ ]:
s[s < 90]

Math       85
Science    88
dtype: int64

In [ ]:
s[s % 2 == 0]

English    90
Science    88
dtype: int64

Series vs Series (Index Alignment Concept)

In [ ]:
s1 = pd.Series([10, 20, 30], index = ["A", "B", "C"])
s2 = pd.Series([1, 2, 3], index = ["A", "B", "C"])

s1 + s2

A    11
B    22
C    33
dtype: int64

In [ ]:
s1 * s2

A    10
B    40
C    90
dtype: int64

In [ ]:
s1 - s2

A     9
B    18
C    27
dtype: int64

Built-in Mathematical Fuctions

In [ ]:
s.count()

np.int64(3)

In [ ]:
s.std()

2.516611478423583

In [ ]:
s.sum()

np.int64(263)

In [ ]:
s.max()

90

Utility fuctions - Very important to remember all the ones that are given below

In [ ]:
s.isnull() # gives null values

Math       False
English    False
Science    False
dtype: bool

In [ ]:
s.replace(10,100) #replace 10 with 100

Math       85
English    90
Science    88
dtype: int64

In [ ]:
s.sort_values() #simple sorting

Math       85
Science    88
English    90
dtype: int64

In [ ]:
s.sort_values(ascending=False) #ascending=False lgaenge to descending dega

English    90
Science    88
Math       85
dtype: int64

In [ ]:
s.unique() #shows unique values

array([85, 90, 88])

DataFrames-Dictioneries

In [ ]:
data = {
    'Name': ['Ali', 'Sara', 'Ahmed'],
    'Age': [20, 22, 21],
    'Marks': [85, 90, 88]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0    Ali   20     85
1   Sara   22     90
2  Ahmed   21     88

From list to lists

In [ ]:
data = [
    ['Ali', 20, 85],
    ['Sara', 22, 90],
    ['Ahmed', 21, 88]
]
# gave data as lists instead of dictioneries
df = pd.DataFrame(data, columns=['Name', 'Age', 'Marks']) # instead of using word index, we use columns here
print(df)

    Name  Age  Marks
0    Ali   20     85
1   Sara   22     90
2  Ahmed   21     88

**Practice 2**
Create a DataFrame with:


*   Student Name
*   Subject
*   Marks






(Make atleast 4 students)

In [ ]:
data = [
    ['Ali', 'Science', 85],
    ['Sara', 'Arts', 90],
    ['Ahmed', 'Maths', 88],
    ['Saad', 'History', 78]
]

sm = pd.DataFrame(data, columns=['Student Name', 'Subject', 'Marks'])
print(sm)

  Student Name  Subject  Marks
0          Ali  Science     85
1         Sara     Arts     90
2        Ahmed    Maths     88
3         Saad  History     78

**Viewing Data**

1. df.head()

returns first n rows, defaults to first 5 rows of a DataFrame

In [ ]:
sm.head()

  Student Name  Subject  Marks
0          Ali  Science     85
1         Sara     Arts     90
2        Ahmed    Maths     88
3         Saad  History     78

2. df.tail()

returns the last n rows, defaults to last 5 rows of a DataFrame

In [ ]:
sm.tail(1)

  Student Name  Subject  Marks
3         Saad  History     78

3. df.info()

provides technical summary

In [ ]:
sm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student Name  4 non-null      object
 1   Subject       4 non-null      object
 2   Marks         4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

4. df.shape

returns a tuple for rows and columns

In [ ]:
sm.shape

(4, 3)

In [ ]:
print(sm.shape[0])

4

In [ ]:
print(sm.shape[1])

3

5. df.columns

returns column headers, print all column names in the order the appear

In [ ]:
print(sm.columns)

Index(['Student Name', 'Subject', 'Marks'], dtype='object')

Data Selection and indexing

1. Select Column

In [ ]:
sm['Student Name']

0      Ali
1     Sara
2    Ahmed
3     Saad
Name: Student Name, dtype: object

2. Select Multiple Column

In [ ]:
sm[['Student Name', 'Marks']]

  Student Name  Marks
0          Ali     85
1         Sara     90
2        Ahmed     88
3         Saad     78

3. Select rows by index

In [ ]:
sm.loc[0]

Student Name        Ali
Subject         Science
Marks                85
Name: 0, dtype: object

In [ ]:
sm.iloc[1] #i iterate k lye use kr rhe hen dusri raw pe janay k lye it needs i

Student Name    Sara
Subject         Arts
Marks             90
Name: 1, dtype: object

Practice 3

In [ ]:
sm['Marks']

0    85
1    90
2    88
3    78
Name: Marks, dtype: int64

In [ ]:
sm.loc[0]

Student Name        Ali
Subject         Science
Marks                85
Name: 0, dtype: object

print marks of first student

Adding and removing columns

1. Add column

In [ ]:
sm['Grade'] = ['A', 'A+', 'A', 'B']
sm

  Student Name  Subject  Marks Grade
0          Ali  Science     85     A
1         Sara     Arts     90    A+
2        Ahmed    Maths     88     A
3         Saad  History     78     B

2. Remove Column

In [ ]:
sm.drop('Grade', axis=1, inplace=True, errors='ignore')
sm

  Student Name  Subject  Marks
0          Ali  Science     85
1         Sara     Arts     90
2        Ahmed    Maths     88
3         Saad  History     78

Handling missing data

Create missing data:

In [ ]:
import numpy as np

data = {
    'Name': ['Ali', 'Sara', 'Ahmed'],
    'Marks': [85, np.nan, 90]
}

df = pd.DataFrame(data)
df

    Name  Marks
0    Ali   85.0
1   Sara    NaN
2  Ahmed   90.0

Detecting Missing values

In [ ]:
df.isnull()

    Name  Marks
0  False  False
1  False   True
2  False  False

In [ ]:
df.isnull().sum()

Name     0
Marks    1
dtype: int64

Remove missing data

In [ ]:
df.dropna()

    Name  Marks
0    Ali   85.0
2  Ahmed   90.0

Fill missing data

In [ ]:
df.fillna(0)

    Name  Marks
0    Ali   85.0
1   Sara    0.0
2  Ahmed   90.0

In [ ]:
df['Marks'].fillna(df['Marks'].mean())

0    85.0
1    87.5
2    90.0
Name: Marks, dtype: float64

Practice 4

---



*   Create a DataFrame with one missing value
*   Replace missing value with average

In [ ]:
data = {
    'Name': ['Ali', 'Sara', 'Ahmed'],
    'Marks': [85, 75, 90],
    'Age': [25, np.nan, 22]
}

df = pd.DataFrame(data)
df

    Name  Marks   Age
0    Ali     85  25.0
1   Sara     75   NaN
2  Ahmed     90  22.0

In [ ]:
df['Age'].fillna(df['Age'].mean())

0    25.0
1    23.5
2    22.0
Name: Age, dtype: float64