<a href="https://colab.research.google.com/github/s-rafia/Samsung-Innovation-Campus-AI-Training/blob/main/Pandas_csv_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

One way to mount using google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

In [ ]:
import pandas as pd

FilePath = "/content/data_Iris.csv"
df = pd.read_csv(FilePath)

df.head()

The way I mounted, by uploading the file in colab

In [ ]:
df = pd.read_csv("/content/data_Iris.csv")

# **1. Data Viewing**

In [ ]:
df.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.tail()

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
df.tail(1)

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
df.shape

(150, 5)

In [ ]:
df.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df.describe()

       Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

# **2. Selection**

In [ ]:
df['Sepal.Length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal.Length, Length: 150, dtype: float64

In [ ]:
df[['Sepal.Length', 'Sepal.Width']]

     Sepal.Length  Sepal.Width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [ ]:
df.iloc[0]

Sepal.Length       5.1
Sepal.Width        3.5
Petal.Length       1.4
Petal.Width        0.2
Species         setosa
Name: 0, dtype: object

In [ ]:
df.iloc[0:5]

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# **3. Conditional Filtering**

In [ ]:
df[df['Species'] == "setosa"]

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.1           1.5          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [ ]:
df[df['Sepal.Length'] > 5]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[118 rows x 5 columns]

# **4. Data Manipulation**

Add New Column

In [ ]:
df['Sepal.Area'] = df['Sepal.Length'] * df['Sepal.Width']
df

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area
0,5.1,3.5,1.4,0.2,setosa,17.85,17.85
1,4.9,3.0,1.4,0.2,setosa,14.70,14.70
2,4.7,3.2,1.3,0.2,setosa,15.04,15.04
3,4.6,3.1,1.5,0.2,setosa,14.26,14.26
4,5.0,3.6,1.4,0.2,setosa,18.00,18.00
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10,20.10
146,6.3,2.5,5.0,1.9,virginica,15.75,15.75
147,6.5,3.0,5.2,2.0,virginica,19.50,19.50
148,6.2,3.4,5.4,2.3,virginica,21.08,21.08
149,5.9,3.0,5.1,1.8,virginica,17.70,17.70

In [ ]:
df['Petal.Size'] = df['Petal.Length'] + df['Petal.Width']
df

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size
0,5.1,3.5,1.4,0.2,setosa,17.85,17.85,1.6
1,4.9,3.0,1.4,0.2,setosa,14.70,14.70,1.6
2,4.7,3.2,1.3,0.2,setosa,15.04,15.04,1.5
3,4.6,3.1,1.5,0.2,setosa,14.26,14.26,1.7
4,5.0,3.6,1.4,0.2,setosa,18.00,18.00,1.6
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10,20.10,7.5
146,6.3,2.5,5.0,1.9,virginica,15.75,15.75,6.9
147,6.5,3.0,5.2,2.0,virginica,19.50,19.50,7.2
148,6.2,3.4,5.4,2.3,virginica,21.08,21.08,7.7
149,5.9,3.0,5.1,1.8,virginica,17.70,17.70,6.9

Drop column

In [ ]:
df.drop("Sepal.Area", axis=1)
# axis = 1 for column, axis = 0 for row

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Petal.Size
0,5.1,3.5,1.4,0.2,setosa,17.85,1.6
1,4.9,3.0,1.4,0.2,setosa,14.70,1.6
2,4.7,3.2,1.3,0.2,setosa,15.04,1.5
3,4.6,3.1,1.5,0.2,setosa,14.26,1.7
4,5.0,3.6,1.4,0.2,setosa,18.00,1.6
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10,7.5
146,6.3,2.5,5.0,1.9,virginica,15.75,6.9
147,6.5,3.0,5.2,2.0,virginica,19.50,7.2
148,6.2,3.4,5.4,2.3,virginica,21.08,7.7
149,5.9,3.0,5.1,1.8,virginica,17.70,6.9

In [ ]:
df.drop("Petal.Size", axis=1)

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area
0,5.1,3.5,1.4,0.2,setosa,17.85,17.85
1,4.9,3.0,1.4,0.2,setosa,14.70,14.70
2,4.7,3.2,1.3,0.2,setosa,15.04,15.04
3,4.6,3.1,1.5,0.2,setosa,14.26,14.26
4,5.0,3.6,1.4,0.2,setosa,18.00,18.00
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10,20.10
146,6.3,2.5,5.0,1.9,virginica,15.75,15.75
147,6.5,3.0,5.2,2.0,virginica,19.50,19.50
148,6.2,3.4,5.4,2.3,virginica,21.08,21.08
149,5.9,3.0,5.1,1.8,virginica,17.70,17.70

# If any column have missing values drop the entire row

In [ ]:
df.dropna()
# Drops a row if ANY column has a missing value, basically ye overall saray columns ko dekh k kisi bhi column
# main koi missing value milegi ise to ye usay remove krdega

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size
0,5.1,3.5,1.4,0.2,setosa,17.85,17.85,1.6
1,4.9,3.0,1.4,0.2,setosa,14.70,14.70,1.6
2,4.7,3.2,1.3,0.2,setosa,15.04,15.04,1.5
3,4.6,3.1,1.5,0.2,setosa,14.26,14.26,1.7
4,5.0,3.6,1.4,0.2,setosa,18.00,18.00,1.6
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10,20.10,7.5
146,6.3,2.5,5.0,1.9,virginica,15.75,15.75,6.9
147,6.5,3.0,5.2,2.0,virginica,19.50,19.50,7.2
148,6.2,3.4,5.4,2.3,virginica,21.08,21.08,7.7
149,5.9,3.0,5.1,1.8,virginica,17.70,17.70,6.9

In [ ]:
df.dropna(subset=["Sepal.Length"])
# agar hmen sirf ek hi column ko target krna ho k sirf agar us column main missing value ae to remove kre us row ko baki kisi bhi column
# main missig value ho usko ignore krde

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size
0,5.1,3.5,1.4,0.2,setosa,17.85,17.85,1.6
1,4.9,3.0,1.4,0.2,setosa,14.70,14.70,1.6
2,4.7,3.2,1.3,0.2,setosa,15.04,15.04,1.5
3,4.6,3.1,1.5,0.2,setosa,14.26,14.26,1.7
4,5.0,3.6,1.4,0.2,setosa,18.00,18.00,1.6
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10,20.10,7.5
146,6.3,2.5,5.0,1.9,virginica,15.75,15.75,6.9
147,6.5,3.0,5.2,2.0,virginica,19.50,19.50,7.2
148,6.2,3.4,5.4,2.3,virginica,21.08,21.08,7.7
149,5.9,3.0,5.1,1.8,virginica,17.70,17.70,6.9

Sorting

In [ ]:
df.sort_values("Sepal.Length")

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size
13,4.3,3.0,1.1,0.1,setosa,12.90,12.90,1.2
8,4.4,2.9,1.4,0.2,setosa,12.76,12.76,1.6
42,4.4,3.2,1.3,0.2,setosa,14.08,14.08,1.5
38,4.4,3.0,1.3,0.2,setosa,13.20,13.20,1.5
41,4.5,2.3,1.3,0.3,setosa,10.35,10.35,1.6
...,...,...,...,...,...,...,...,...
122,7.7,2.8,6.7,2.0,virginica,21.56,21.56,8.7
117,7.7,3.8,6.7,2.2,virginica,29.26,29.26,8.9
118,7.7,2.6,6.9,2.3,virginica,20.02,20.02,9.2
135,7.7,3.0,6.1,2.3,virginica,23.10,23.10,8.4
131,7.9,3.8,6.4,2.0,virginica,30.02,30.02,8.4

Sorting (Descending)

In [ ]:
df.sort_values("Sepal.Length", ascending=False)

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size
131,7.9,3.8,6.4,2.0,virginica,30.02,30.02,8.4
122,7.7,2.8,6.7,2.0,virginica,21.56,21.56,8.7
118,7.7,2.6,6.9,2.3,virginica,20.02,20.02,9.2
117,7.7,3.8,6.7,2.2,virginica,29.26,29.26,8.9
135,7.7,3.0,6.1,2.3,virginica,23.10,23.10,8.4
...,...,...,...,...,...,...,...,...
41,4.5,2.3,1.3,0.3,setosa,10.35,10.35,1.6
42,4.4,3.2,1.3,0.2,setosa,14.08,14.08,1.5
8,4.4,2.9,1.4,0.2,setosa,12.76,12.76,1.6
38,4.4,3.0,1.3,0.2,setosa,13.20,13.20,1.5
13,4.3,3.0,1.1,0.1,setosa,12.90,12.90,1.2

Update Value - loc[row, column]

In [ ]:
df.loc[0, "Sepal.Length"] = 10
df

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size
0,10.0,3.5,1.4,0.2,setosa,17.85,17.85,1.6
1,4.9,3.0,1.4,0.2,setosa,14.70,14.70,1.6
2,4.7,3.2,1.3,0.2,setosa,15.04,15.04,1.5
3,4.6,3.1,1.5,0.2,setosa,14.26,14.26,1.7
4,5.0,3.6,1.4,0.2,setosa,18.00,18.00,1.6
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10,20.10,7.5
146,6.3,2.5,5.0,1.9,virginica,15.75,15.75,6.9
147,6.5,3.0,5.2,2.0,virginica,19.50,19.50,7.2
148,6.2,3.4,5.4,2.3,virginica,21.08,21.08,7.7
149,5.9,3.0,5.1,1.8,virginica,17.70,17.70,6.9

Duplicates - In every column it compares from the previous rows to check if the value is repeated in th column

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

Number of duplicated files

In [ ]:
df.duplicated().value_counts()

False    147
True       3
Name: count, dtype: int64

Remove Duplicates

In [ ]:
df.drop_duplicates()

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size
0,10.0,3.5,1.4,0.2,setosa,17.85,17.85,1.6
1,4.9,3.0,1.4,0.2,setosa,14.70,14.70,1.6
2,4.7,3.2,1.3,0.2,setosa,15.04,15.04,1.5
3,4.6,3.1,1.5,0.2,setosa,14.26,14.26,1.7
4,5.0,3.6,1.4,0.2,setosa,18.00,18.00,1.6
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10,20.10,7.5
146,6.3,2.5,5.0,1.9,virginica,15.75,15.75,6.9
147,6.5,3.0,5.2,2.0,virginica,19.50,19.50,7.2
148,6.2,3.4,5.4,2.3,virginica,21.08,21.08,7.7
149,5.9,3.0,5.1,1.8,virginica,17.70,17.70,6.9

Show duplicate rows

In [ ]:
df[df.duplicated()]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size
34,4.9,3.1,1.5,0.1,setosa,15.19,15.19,1.6
37,4.9,3.1,1.5,0.1,setosa,15.19,15.19,1.6
142,5.8,2.7,5.1,1.9,virginica,15.66,15.66,7.0

Row difference

In [ ]:
print("Before:", df.shape)
df = df.drop_duplicates()
print("After", df.shape)

Before: (150, 8)
After (147, 8)

# **Practice 5**

Show first 10 rows

In [ ]:
df.head(10)

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size
0,10.0,3.5,1.4,0.2,setosa,17.85,17.85,1.6
1,4.9,3.0,1.4,0.2,setosa,14.70,14.70,1.6
2,4.7,3.2,1.3,0.2,setosa,15.04,15.04,1.5
3,4.6,3.1,1.5,0.2,setosa,14.26,14.26,1.7
4,5.0,3.6,1.4,0.2,setosa,18.00,18.00,1.6
5,5.4,3.9,1.7,0.4,setosa,21.06,21.06,2.1
6,4.6,3.4,1.4,0.3,setosa,15.64,15.64,1.7
7,5.0,3.4,1.5,0.2,setosa,17.00,17.00,1.7
8,4.4,2.9,1.4,0.2,setosa,12.76,12.76,1.6
9,4.9,3.1,1.5,0.1,setosa,15.19,15.19,1.6

show petal_length column

In [ ]:
df['Petal.Length']

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ...
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: Petal.Length, Length: 147, dtype: float64

Filter rows where spices = "versicolor'

In [ ]:
df[df['Species'] == "versicolor"]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size
50,7.0,3.2,4.7,1.4,versicolor,22.40,22.40,6.1
51,6.4,3.2,4.5,1.5,versicolor,20.48,20.48,6.0
52,6.9,3.1,4.9,1.5,versicolor,21.39,21.39,6.4
53,5.5,2.3,4.0,1.3,versicolor,12.65,12.65,5.3
54,6.5,2.8,4.6,1.5,versicolor,18.20,18.20,6.1
55,5.7,2.8,4.5,1.3,versicolor,15.96,15.96,5.8
56,6.3,3.3,4.7,1.6,versicolor,20.79,20.79,6.3
57,4.9,2.4,3.3,1.0,versicolor,11.76,11.76,4.3
58,6.6,2.9,4.6,1.3,versicolor,19.14,19.14,5.9
59,5.2,2.7,3.9,1.4,versicolor,14.04,14.04,5.3
60,5.0,2.0,3.5,1.0,versicolor,10.00,10.00,4.5
61,5.9,3.0,4.2,1.5,versicolor,17.70,17.70,5.7
62,6.0,2.2,4.0,1.0,versicolor,13.20,13.20,5.0
63,6.1,2.9,4.7,1.4,versicolor,17.69,17.69,6.1
64,5.6,2.9,3.6,1.3,versicolor,16.24,16.24,4.9
65,6.7,3.1,4.4,1.4,versicolor,20.77,20.77,5.8
66,5.6,3.0,4.5,1.5,versicolor,16.80,16.80,6.0
67,5.8,2.7,4.1,1.0,versicolor,15.66,15.66,5.1
68,6.2,2.2,4.5,1.5,versicolor,13.64,13.64,6.0
69,5.6,2.5,3.9,1.1,versicolor,14.00,14.00,5.0
70,5.9,3.2,4.8,1.8,versicolor,18.88,18.88,6.6
71,6.1,2.8,4.0,1.3,versicolor,17.08,17.08,5.3
72,6.3,2.5,4.9,1.5,versicolor,15.75,15.75,6.4
73,6.1,2.8,4.7,1.2,versicolor,17.08,17.08,5.9
74,6.4,2.9,4.3,1.3,versicolor,18.56,18.56,5.6
75,6.6,3.0,4.4,1.4,versicolor,19.80,19.80,5.8
76,6.8,2.8,4.8,1.4,versicolor,19.04,19.04,6.2
77,6.7,3.0,5.0,1.7,versicolor,20.10,20.10,6.7
78,6.0,2.9,4.5,1.5,versicolor,17.40,17.40,6.0
79,5.7,2.6,3.5,1.0,versicolor,14.82,14.82,4.5
80,5.5,2.4,3.8,1.1,versicolor,13.20,13.20,4.9
81,5.5,2.4,3.7,1.0,versicolor,13.20,13.20,4.7
82,5.8,2.7,3.9,1.2,versicolor,15.66,15.66,5.1
83,6.0,2.7,5.1,1.6,versicolor,16.20,16.20,6.7
84,5.4,3.0,4.5,1.5,versicolor,16.20,16.20,6.0
85,6.0,3.4,4.5,1.6,versicolor,20.40,20.40,6.1
86,6.7,3.1,4.7,1.5,versicolor,20.77,20.77,6.2
87,6.3,2.3,4.4,1.3,versicolor,14.49,14.49,5.7
88,5.6,3.0,4.1,1.3,versicolor,16.80,16.80,5.4
89,5.5,2.5,4.0,1.3,versicolor,13.75,13.75,5.3
90,5.5,2.6,4.4,1.2,versicolor,14.30,14.30,5.6
91,6.1,3.0,4.6,1.4,versicolor,18.30,18.30,6.0
92,5.8,2.6,4.0,1.2,versicolor,15.08,15.08,5.2
93,5.0,2.3,3.3,1.0,versicolor,11.50,11.50,4.3
94,5.6,2.7,4.2,1.3,versicolor,15.12,15.12,5.5
95,5.7,3.0,4.2,1.2,versicolor,17.10,17.10,5.4
96,5.7,2.9,4.2,1.3,versicolor,16.53,16.53,5.5
97,6.2,2.9,4.3,1.3,versicolor,17.98,17.98,5.6
98,5.1,2.5,3.0,1.1,versicolor,12.75,12.75,4.1
99,5.7,2.8,4.1,1.3,versicolor,15.96,15.96,5.4

Create petal_area column

In [ ]:
df['petal_area'] = df['Petal.Length'] * df['Petal.Width']
df

/tmp/ipython-input-235/380168728.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['petal_area'] = df['Petal.Length'] * df['Petal.Width']

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size,petal_area
0,10.0,3.5,1.4,0.2,setosa,17.85,17.85,1.6,0.28
1,4.9,3.0,1.4,0.2,setosa,14.70,14.70,1.6,0.28
2,4.7,3.2,1.3,0.2,setosa,15.04,15.04,1.5,0.26
3,4.6,3.1,1.5,0.2,setosa,14.26,14.26,1.7,0.30
4,5.0,3.6,1.4,0.2,setosa,18.00,18.00,1.6,0.28
...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,20.10,20.10,7.5,11.96
146,6.3,2.5,5.0,1.9,virginica,15.75,15.75,6.9,9.50
147,6.5,3.0,5.2,2.0,virginica,19.50,19.50,7.2,10.40
148,6.2,3.4,5.4,2.3,virginica,21.08,21.08,7.7,12.42
149,5.9,3.0,5.1,1.8,virginica,17.70,17.70,6.9,9.18

Sort by petal_width descending

In [ ]:
df.sort_values("Petal.Width", ascending=False)

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,Sepal_area,Sepal.Area,Petal.Size,petal_area
100,6.3,3.3,6.0,2.5,virginica,20.79,20.79,8.5,15.00
144,6.7,3.3,5.7,2.5,virginica,22.11,22.11,8.2,14.25
109,7.2,3.6,6.1,2.5,virginica,25.92,25.92,8.6,15.25
114,5.8,2.8,5.1,2.4,virginica,16.24,16.24,7.5,12.24
140,6.7,3.1,5.6,2.4,virginica,20.77,20.77,8.0,13.44
...,...,...,...,...,...,...,...,...,...
39,5.1,3.4,1.5,0.2,setosa,17.34,17.34,1.7,0.30
12,4.8,3.0,1.4,0.1,setosa,14.40,14.40,1.5,0.14
13,4.3,3.0,1.1,0.1,setosa,12.90,12.90,1.2,0.11
9,4.9,3.1,1.5,0.1,setosa,15.19,15.19,1.6,0.15
32,5.2,4.1,1.5,0.1,setosa,21.32,21.32,1.6,0.15

Show average sepal_length

In [ ]:
df['Sepal.Length'].mean()

np.float64(5.889795918367347)

# **Group by and Aggregation**

groupby

In [ ]:
df.groupby("Species").mean()

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Sepal_area,Sepal.Area,Petal.Size,petal_area
Species,,,,,,,,
setosa,5.112500,3.431250,1.462500,0.250000,17.292917,17.292917,1.712500,0.371667
versicolor,5.936000,2.770000,4.260000,1.326000,16.526200,16.526200,5.586000,5.720400
virginica,6.604082,2.979592,5.561224,2.028571,19.766735,19.766735,7.589796,11.328980

Aggregation

In [ ]:
df.groupby("Species").agg(["mean", "max", "min"])

           Sepal.Length            Sepal.Width           Petal.Length       \
                   mean   max  min        mean  max  min         mean  max
Species
setosa         5.112500  10.0  4.3    3.431250  4.4  2.3     1.462500  1.9
versicolor     5.936000   7.0  4.9    2.770000  3.4  2.0     4.260000  5.1
virginica      6.604082   7.9  4.9    2.979592  3.8  2.2     5.561224  6.9

                Petal.Width  ... Sepal_area Sepal.Area                \
            min        mean  ...        min       mean    max    min
Species                      ...
setosa      1.0    0.250000  ...      10.35  17.292917  25.08  10.35
versicolor  3.0    1.326000  ...      10.00  16.526200  22.40  10.00
virginica   4.5    2.028571  ...      12.25  19.766735  30.02  12.25

           Petal.Size           petal_area
                 mean  max  min       mean    max   min
Species
setosa       1.712500  2.3  1.2   0.371667   0.96  0.11
versicolor   5.586000  6.7  4.1   5.720400   8.64  3.30
virginica    7.589796  9.2  6.2  11.328980  15.87  7.50

[3 rows x 24 columns]

Count Values - Show the count

In [ ]:
df['Species'].value_counts()

Species
versicolor    50
virginica     49
setosa        48
Name: count, dtype: int64

# **Pivot Tables**

In [ ]:
pd.pivot_table(df,
               values = "Sepal.Length",
               index = "Species",
               aggfunc = "mean")

            Sepal.Length
Species
setosa          5.112500
versicolor      5.936000
virginica       6.604082

In [ ]:
pd.pivot_table(df,
               values = "Sepal.Length",
               index = "Species",
               aggfunc = ["mean", "nunique"])

                   mean      nunique
           Sepal.Length Sepal.Length
Species
setosa         5.112500           16
versicolor     5.936000           21
virginica      6.604082           21